### ISSUE TITLE
How did i run it?

### ISSUE THREAD

**Issue by florian-asche** [florian-asche/docker-rundeck-ansible#1]
I did run it with this compose file:

```
version: '3.4'

networks:
  internal:
    external:
      name: atlantis-dockernetwork

services:
    rundeck:
        image: florian9931/rundeck-ansible:4.8.0
        links:
          - postgres
        environment:
            RUNDECK_DATABASE_DRIVER: org.postgresql.Driver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: rundeck
            RUNDECK_DATABASE_URL: jdbc:postgresql://postgres/rundeck?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
            RUNDECK_GRAILS_URL: http://192.168.0.4:4440
            #RUNDECK_SERVER_FORWARDED: 'true'
            # GRAILS = URL TO SYSTEM
        volumes:
          - ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
          - rundeck_data:/home/rundeck/server/data
          - rundeck_projects:/home/rundeck/projects
        ports:
          - 4440:4440
    vscodeserver:
        image: linuxserver/code-server:latest
        environment:
          - PUID=1500
          - PGID=1500
          - TZ=Europe/Berlin
          - PASSWORD=password #optional
          - HASHED_PASSWORD= #optional
          #- SUDO_PASSWORD=password #optional
          #- SUDO_PASSWORD_HASH= #optional
          #- PROXY_DOMAIN=code-server.my.domain #optional
          - DEFAULT_WORKSPACE=/config/workspace #optional
        volumes:
          - rundeck_projects:/config
        ports:
          - 8443:8443
        restart: unless-stopped

    ansible:
        image: florian9931/ansible-ssh:latest
        #links:
        #  - rundeck
        #environment:
        volumes:
          - ansible_ssh:/home/ansible/.ssh/
        networks:
          - internal
        ports:
          - "12022:22"
    postgres:
        image: postgres
        expose:
          - 5432
        environment:
          - POSTGRES_DB=rundeck
          - POSTGRES_USER=rundeck
          - POSTGRES_PASSWORD=rundeck
        volumes:
          - dbdata:/var/lib/postgresql/data

volumes:
    dbdata:
    ansible_ssh:
    rundeck_data:
    rundeck_projects: 
```

But sadly i came a across this bug: https://github.com/rundeck-plugins/ansible-plugin/issues/298
The needed ansible rundeck plugin is not capable to use ssh keys with a password. Since i am focused on security in this project i wont continue from here on.
